---
- name: Setup Apache Web Server on target-server
  hosts: targetserver
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Copy custom index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
